# Шаг 1: Билд приложения
FROM golang:1.22 AS build

WORKDIR /app

# Копируем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходники проекта
COPY . .

# Сборка бинарника
WORKDIR /app/cmd
RUN CGO_ENABLED=0 GOOS=linux go build -o main

# Шаг 2: Минимальный образ для запуска
FROM alpine:latest

# Установка сертификатов
RUN apk add --no-cache ca-certificates

WORKDIR /root/

# Копируем бинарник и файл окружения
COPY --from=build /app/cmd/main .
COPY --from=build /app/.env_local .

# Указываем порт и команду запуска
CMD ["./main"]
