version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: go-parser-dpa
    ports:
      - "3005:3005"
    volumes:
      - .:/app
    env_file:
      - .env_local
    environment:
      - SERVER_PORT=:3005
      - DB_URL=postgres://root:root@postgres:5432/stochmpred
      - DPA_SERVER=http://10.10.17.153/api
      - CLICK_URL=clickhouse://default:@clickhouse:9000/default?secure=false&dial_timeout=10s&read_timeout=20s
      - CLICK_USER=default
      - CLICK_PASS=
    depends_on:
      - postgres
      - clickhouse
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    container_name: stochmpred_db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=stochmpred
    ports:
      - "5432:5432"
    volumes:
      - ./db-volumes/database/postgres:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  clickhouse:
    image: "clickhouse/clickhouse-server:23.4"
    user: "101:101"
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ./db-volumes/database/clickhouse:/var/lib/clickhouse/data
      - ./init-db/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./init-db/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on:
      - clickhouse-keeper
    networks:
      - app-network

  clickhouse-keeper:
    image: "clickhouse/clickhouse-keeper:23.4-alpine"
    user: "101:101"
    container_name: clickhouse-keeper
    hostname: clickhouse-keeper
    volumes:
      - ./init-db/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - "9181:9181"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
